version: '3.7'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=start#123
    ports:
      - '5432:5432'
    volumes:
      - ./01-create-item-table.sql:/docker-entrypoint-initdb.d/01-create-item-table.sql